### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Ewg777** [mixmaxhq/eb-fix-npm#11]
node_modules\install-files\src\hostPackageDir.js:12
  var pathComponents = file.split(path.sep);
                           ^
TypeError: Cannot read property 'split' of undefined
    at hostPackageDir (C:\Users\user\untitled\node_modules\install-files\src\hostPackageDir.js:12:28)
    at installFiles (C:\Users\user\untitled\node_modules\install-files\src\index.js:45:35)
    at Object.<anonymous> (C:\Users\user\untitled\node_modules\install-files\bin\install-files.js:16:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "eb-fix-npm" "--save-dev"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! eb-fix-npm@1.2.5 install: `install-files source`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the eb-fix-npm@1.2.5 install script 'install-files source'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the eb-fix-npm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     install-files source
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs eb-fix-npm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls eb-fix-npm
npm ERR! There is likely additional logging output above.

**Comment by sunilgulabani** [comment]
Any fix for this issue?

**Comment by wearhere** [comment]
I think this is an issue in `install-files`, filed https://github.com/mixmaxhq/install-files/issues/14.

**Comment by Blakeinstein** [comment]
Did any of you guys manage to resolve this?
